server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: toto
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource


    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: validate

web-client:
  url: http://localhost:4200

